// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2iFQaXFhRRwiRxHB_wHoSkqYN8AeH2s',
    appId: '1:217160457136:web:a5bb00d177f467faca9475',
    messagingSenderId: '217160457136',
    projectId: 'chat-app-v1-d2cb4',
    authDomain: 'chat-app-v1-d2cb4.firebaseapp.com',
    storageBucket: 'chat-app-v1-d2cb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwnXzA5eAxkJVJO6bfYbNUuMVQsRC8hc',
    appId: '1:217160457136:android:3cce90a9a702559eca9475',
    messagingSenderId: '217160457136',
    projectId: 'chat-app-v1-d2cb4',
    storageBucket: 'chat-app-v1-d2cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW2jTXYAIbEK1R7QuO0EpCUpfhQrBCdEQ',
    appId: '1:217160457136:ios:f79e4b1ab0b78205ca9475',
    messagingSenderId: '217160457136',
    projectId: 'chat-app-v1-d2cb4',
    storageBucket: 'chat-app-v1-d2cb4.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW2jTXYAIbEK1R7QuO0EpCUpfhQrBCdEQ',
    appId: '1:217160457136:ios:f79e4b1ab0b78205ca9475',
    messagingSenderId: '217160457136',
    projectId: 'chat-app-v1-d2cb4',
    storageBucket: 'chat-app-v1-d2cb4.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq2iFQaXFhRRwiRxHB_wHoSkqYN8AeH2s',
    appId: '1:217160457136:web:60b486418ae9e664ca9475',
    messagingSenderId: '217160457136',
    projectId: 'chat-app-v1-d2cb4',
    authDomain: 'chat-app-v1-d2cb4.firebaseapp.com',
    storageBucket: 'chat-app-v1-d2cb4.appspot.com',
  );
}
